apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: ns-${NS}-to-all
  namespace: monitor
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: monitor
  placement:
    clusterAffinity:
      clusterNames:
        - ${HOST_CLUSTER_NAME}
        - ${MEMBER_CLUSTER_NAME}
