// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/scheduler/framework/plugins/sdi/analysisengine.proto

package sdi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisEngine_GetScores_FullMethodName = "/sdi.AnalysisEngine/GetScores"
)

// AnalysisEngineClient is the client API for AnalysisEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalysisEngineClient interface {
	GetScores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Scores, error)
}

type analysisEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisEngineClient(cc grpc.ClientConnInterface) AnalysisEngineClient {
	return &analysisEngineClient{cc}
}

func (c *analysisEngineClient) GetScores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Scores, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scores)
	err := c.cc.Invoke(ctx, AnalysisEngine_GetScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisEngineServer is the server API for AnalysisEngine service.
// All implementations must embed UnimplementedAnalysisEngineServer
// for forward compatibility.
type AnalysisEngineServer interface {
	GetScores(context.Context, *emptypb.Empty) (*Scores, error)
	mustEmbedUnimplementedAnalysisEngineServer()
}

// UnimplementedAnalysisEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisEngineServer struct{}

func (UnimplementedAnalysisEngineServer) GetScores(context.Context, *emptypb.Empty) (*Scores, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScores not implemented")
}
func (UnimplementedAnalysisEngineServer) mustEmbedUnimplementedAnalysisEngineServer() {}
func (UnimplementedAnalysisEngineServer) testEmbeddedByValue()                        {}

// UnsafeAnalysisEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisEngineServer will
// result in compilation errors.
type UnsafeAnalysisEngineServer interface {
	mustEmbedUnimplementedAnalysisEngineServer()
}

func RegisterAnalysisEngineServer(s grpc.ServiceRegistrar, srv AnalysisEngineServer) {
	// If the following call pancis, it indicates UnimplementedAnalysisEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisEngine_ServiceDesc, srv)
}

func _AnalysisEngine_GetScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisEngineServer).GetScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisEngine_GetScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisEngineServer).GetScores(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisEngine_ServiceDesc is the grpc.ServiceDesc for AnalysisEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdi.AnalysisEngine",
	HandlerType: (*AnalysisEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScores",
			Handler:    _AnalysisEngine_GetScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/scheduler/framework/plugins/sdi/analysisengine.proto",
}
