# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_service_pb2 as analysis__service__pb2

GRPC_GENERATED_VERSION = '1.59.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = False

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analysis_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """분석 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTurtlebot = channel.unary_unary(
                '/analysis.AnalysisService/CreateTurtlebot',
                request_serializer=analysis__service__pb2.CreateTurtlebotRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.CreateTurtlebotResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/analysis.AnalysisService/GetDeviceStatus',
                request_serializer=analysis__service__pb2.GetDeviceStatusRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.GetDeviceStatusResponse.FromString,
                _registered_method=True)
        self.UpdateFromInflux = channel.unary_unary(
                '/analysis.AnalysisService/UpdateFromInflux',
                request_serializer=analysis__service__pb2.UpdateFromInfluxRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.UpdateFromInfluxResponse.FromString,
                _registered_method=True)
        self.GetAllDevices = channel.unary_unary(
                '/analysis.AnalysisService/GetAllDevices',
                request_serializer=analysis__service__pb2.GetAllDevicesRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.GetAllDevicesResponse.FromString,
                _registered_method=True)
        self.GetBatteryStatus = channel.unary_unary(
                '/analysis.AnalysisService/GetBatteryStatus',
                request_serializer=analysis__service__pb2.GetBatteryStatusRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.GetBatteryStatusResponse.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/analysis.AnalysisService/EmergencyStop',
                request_serializer=analysis__service__pb2.EmergencyStopRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.EmergencyStopResponse.FromString,
                _registered_method=True)
        self.AnalyzeMaleMission = channel.unary_unary(
                '/analysis.AnalysisService/AnalyzeMaleMission',
                request_serializer=analysis__service__pb2.AnalyzeMaleMissionRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.AnalyzeMaleMissionResponse.FromString,
                _registered_method=True)
        self.AnalyzeAccuracy = channel.unary_unary(
                '/analysis.AnalysisService/AnalyzeAccuracy',
                request_serializer=analysis__service__pb2.AnalyzeAccuracyRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.AnalyzeAccuracyResponse.FromString,
                _registered_method=True)
        self.AnalyzeLatency = channel.unary_unary(
                '/analysis.AnalysisService/AnalyzeLatency',
                request_serializer=analysis__service__pb2.AnalyzeLatencyRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.AnalyzeLatencyResponse.FromString,
                _registered_method=True)
        self.GetDeviceScore = channel.unary_unary(
                '/analysis.AnalysisService/GetDeviceScore',
                request_serializer=analysis__service__pb2.GetDeviceScoreRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.GetDeviceScoreResponse.FromString,
                _registered_method=True)
        self.GetFleetAnalysis = channel.unary_unary(
                '/analysis.AnalysisService/GetFleetAnalysis',
                request_serializer=analysis__service__pb2.GetFleetAnalysisRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.GetFleetAnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeDevice = channel.unary_unary(
                '/analysis.AnalysisService/AnalyzeDevice',
                request_serializer=analysis__service__pb2.AnalyzeDeviceRequest.SerializeToString,
                response_deserializer=analysis__service__pb2.AnalyzeDeviceResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """분석 서비스 정의
    """

    def CreateTurtlebot(self, request, context):
        """기존 모니터링 서비스들
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFromInflux(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatteryStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeMaleMission(self, request, context):
        """새로운 분석 및 평가 서비스들
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAccuracy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLatency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFleetAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTurtlebot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTurtlebot,
                    request_deserializer=analysis__service__pb2.CreateTurtlebotRequest.FromString,
                    response_serializer=analysis__service__pb2.CreateTurtlebotResponse.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=analysis__service__pb2.GetDeviceStatusRequest.FromString,
                    response_serializer=analysis__service__pb2.GetDeviceStatusResponse.SerializeToString,
            ),
            'UpdateFromInflux': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFromInflux,
                    request_deserializer=analysis__service__pb2.UpdateFromInfluxRequest.FromString,
                    response_serializer=analysis__service__pb2.UpdateFromInfluxResponse.SerializeToString,
            ),
            'GetAllDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllDevices,
                    request_deserializer=analysis__service__pb2.GetAllDevicesRequest.FromString,
                    response_serializer=analysis__service__pb2.GetAllDevicesResponse.SerializeToString,
            ),
            'GetBatteryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatteryStatus,
                    request_deserializer=analysis__service__pb2.GetBatteryStatusRequest.FromString,
                    response_serializer=analysis__service__pb2.GetBatteryStatusResponse.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=analysis__service__pb2.EmergencyStopRequest.FromString,
                    response_serializer=analysis__service__pb2.EmergencyStopResponse.SerializeToString,
            ),
            'AnalyzeMaleMission': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeMaleMission,
                    request_deserializer=analysis__service__pb2.AnalyzeMaleMissionRequest.FromString,
                    response_serializer=analysis__service__pb2.AnalyzeMaleMissionResponse.SerializeToString,
            ),
            'AnalyzeAccuracy': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAccuracy,
                    request_deserializer=analysis__service__pb2.AnalyzeAccuracyRequest.FromString,
                    response_serializer=analysis__service__pb2.AnalyzeAccuracyResponse.SerializeToString,
            ),
            'AnalyzeLatency': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLatency,
                    request_deserializer=analysis__service__pb2.AnalyzeLatencyRequest.FromString,
                    response_serializer=analysis__service__pb2.AnalyzeLatencyResponse.SerializeToString,
            ),
            'GetDeviceScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceScore,
                    request_deserializer=analysis__service__pb2.GetDeviceScoreRequest.FromString,
                    response_serializer=analysis__service__pb2.GetDeviceScoreResponse.SerializeToString,
            ),
            'GetFleetAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFleetAnalysis,
                    request_deserializer=analysis__service__pb2.GetFleetAnalysisRequest.FromString,
                    response_serializer=analysis__service__pb2.GetFleetAnalysisResponse.SerializeToString,
            ),
            'AnalyzeDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDevice,
                    request_deserializer=analysis__service__pb2.AnalyzeDeviceRequest.FromString,
                    response_serializer=analysis__service__pb2.AnalyzeDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """분석 서비스 정의
    """

    @staticmethod
    def CreateTurtlebot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/CreateTurtlebot',
            analysis__service__pb2.CreateTurtlebotRequest.SerializeToString,
            analysis__service__pb2.CreateTurtlebotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetDeviceStatus',
            analysis__service__pb2.GetDeviceStatusRequest.SerializeToString,
            analysis__service__pb2.GetDeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFromInflux(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/UpdateFromInflux',
            analysis__service__pb2.UpdateFromInfluxRequest.SerializeToString,
            analysis__service__pb2.UpdateFromInfluxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetAllDevices',
            analysis__service__pb2.GetAllDevicesRequest.SerializeToString,
            analysis__service__pb2.GetAllDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatteryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetBatteryStatus',
            analysis__service__pb2.GetBatteryStatusRequest.SerializeToString,
            analysis__service__pb2.GetBatteryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/EmergencyStop',
            analysis__service__pb2.EmergencyStopRequest.SerializeToString,
            analysis__service__pb2.EmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeMaleMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/AnalyzeMaleMission',
            analysis__service__pb2.AnalyzeMaleMissionRequest.SerializeToString,
            analysis__service__pb2.AnalyzeMaleMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeAccuracy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/AnalyzeAccuracy',
            analysis__service__pb2.AnalyzeAccuracyRequest.SerializeToString,
            analysis__service__pb2.AnalyzeAccuracyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeLatency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/AnalyzeLatency',
            analysis__service__pb2.AnalyzeLatencyRequest.SerializeToString,
            analysis__service__pb2.AnalyzeLatencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetDeviceScore',
            analysis__service__pb2.GetDeviceScoreRequest.SerializeToString,
            analysis__service__pb2.GetDeviceScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFleetAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetFleetAnalysis',
            analysis__service__pb2.GetFleetAnalysisRequest.SerializeToString,
            analysis__service__pb2.GetFleetAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/AnalyzeDevice',
            analysis__service__pb2.AnalyzeDeviceRequest.SerializeToString,
            analysis__service__pb2.AnalyzeDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
