// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: pkg/scheduler/framework/plugins/sdi/analysisengine.proto

package sdi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccuracyScore int32                  `protobuf:"varint,1,opt,name=accuracy_score,json=accuracyScore,proto3" json:"accuracy_score,omitempty"`
	LatencyScore  int32                  `protobuf:"varint,2,opt,name=latency_score,json=latencyScore,proto3" json:"latency_score,omitempty"`
	EnergyScore   int32                  `protobuf:"varint,3,opt,name=energy_score,json=energyScore,proto3" json:"energy_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scores) Reset() {
	*x = Scores{}
	mi := &file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scores) ProtoMessage() {}

func (x *Scores) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scores.ProtoReflect.Descriptor instead.
func (*Scores) Descriptor() ([]byte, []int) {
	return file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescGZIP(), []int{0}
}

func (x *Scores) GetAccuracyScore() int32 {
	if x != nil {
		return x.AccuracyScore
	}
	return 0
}

func (x *Scores) GetLatencyScore() int32 {
	if x != nil {
		return x.LatencyScore
	}
	return 0
}

func (x *Scores) GetEnergyScore() int32 {
	if x != nil {
		return x.EnergyScore
	}
	return 0
}

var File_pkg_scheduler_framework_plugins_sdi_analysisengine_proto protoreflect.FileDescriptor

const file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDesc = "" +
	"\n" +
	"8pkg/scheduler/framework/plugins/sdi/analysisengine.proto\x12\x03sdi\x1a\x1bgoogle/protobuf/empty.proto\"w\n" +
	"\x06Scores\x12%\n" +
	"\x0eaccuracy_score\x18\x01 \x01(\x05R\raccuracyScore\x12#\n" +
	"\rlatency_score\x18\x02 \x01(\x05R\flatencyScore\x12!\n" +
	"\fenergy_score\x18\x03 \x01(\x05R\venergyScore2B\n" +
	"\x0eAnalysisEngine\x120\n" +
	"\tGetScores\x12\x16.google.protobuf.Empty\x1a\v.sdi.ScoresBGZEgithub.com/karmada-io/karmada/pkg/scheduler/framework/plugins/sdi;sdib\x06proto3"

var (
	file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescOnce sync.Once
	file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescData []byte
)

func file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescGZIP() []byte {
	file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescOnce.Do(func() {
		file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDesc), len(file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDesc)))
	})
	return file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDescData
}

var file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_goTypes = []any{
	(*Scores)(nil),        // 0: sdi.Scores
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_depIdxs = []int32{
	1, // 0: sdi.AnalysisEngine.GetScores:input_type -> google.protobuf.Empty
	0, // 1: sdi.AnalysisEngine.GetScores:output_type -> sdi.Scores
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_init() }
func file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_init() {
	if File_pkg_scheduler_framework_plugins_sdi_analysisengine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDesc), len(file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_goTypes,
		DependencyIndexes: file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_depIdxs,
		MessageInfos:      file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_msgTypes,
	}.Build()
	File_pkg_scheduler_framework_plugins_sdi_analysisengine_proto = out.File
	file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_goTypes = nil
	file_pkg_scheduler_framework_plugins_sdi_analysisengine_proto_depIdxs = nil
}
